version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    restart: always
    deploy:
      resources:
        limits:
          memory: 125M
    ports:
       - "1883:1883"
       - "9001:9001"
    volumes:
      - ./data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log
    networks:
      - testnet
  
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    privileged: true
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - mosquitto
    networks:
      - testnet

#  influxdb:
#    container_name: influxdb
#    image: influxdb/influxdb:latest
#    hostname: influxdb
#    ports:
#      - "8086:8086"
#    volumes:
#      - ./data/influxdb/data:/var/lib/influxdb
#      - ./data/influxdb:/etc/influxdb/
#    restart: always
#    networks:
#      - testnet

#  telegraf:
#    container_name: telegraf
#    hostname: telegraf
#    image: telegraf
#    volumes:
#      - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
#      - /var/run/docker.sock:/var/run/docker.sock
#    restart: always
#    depends_on:
#      - mosquitto
#      - influxdb
#    networks:
#      - testnet
    
networks:
  testnet:
    driver: bridge
